import type { LucideIcon } from 'lucide-react'
import {
  AlertTriangle,
  Bot,
  Brain,
  Building2,
  CheckCircle2,
  Cloud,
  Code2,
  Cpu,
  FileCode2,
  FolderTree,
  GraduationCap,
  Layers,
  MessageSquare,
  PencilRuler,
  Rocket,
  Scale,
  Shield,
  Sparkles,
  Target,
  TrendingUp,
  Users,
  Wrench,
  Zap,
  GitBranch,
  CircleDollarSign,
  Landmark,
  Network,
  Eye,
  Lock,
  BookOpen,
  Gauge,
  UserRound,
  Briefcase,
  School,
  Building,
  Crown,
  ArrowRightLeft,
  Bug,
  Blocks,
  Terminal,
  Puzzle,
} from 'lucide-react'

export const iconMap = {
  sparkles: Sparkles,
  bot: Bot,
  brain: Brain,
  code: Code2,
  message: MessageSquare,
  zap: Zap,
  layers: Layers,
  folder: FolderTree,
  cloud: Cloud,
  users: Users,
  building: Building2,
  rocket: Rocket,
  trending: TrendingUp,
  target: Target,
  shield: Shield,
  alert: AlertTriangle,
  check: CheckCircle2,
  cpu: Cpu,
  wrench: Wrench,
  scale: Scale,
  graduation: GraduationCap,
  pencil: PencilRuler,
  file: FileCode2,
  git: GitBranch,
  dollar: CircleDollarSign,
  landmark: Landmark,
  network: Network,
  eye: Eye,
  lock: Lock,
  book: BookOpen,
  gauge: Gauge,
  user: UserRound,
  briefcase: Briefcase,
  school: School,
  office: Building,
  crown: Crown,
  swap: ArrowRightLeft,
  bug: Bug,
  blocks: Blocks,
  terminal: Terminal,
  puzzle: Puzzle,
} as const

export type IconName = keyof typeof iconMap

export function Icon({
  name,
  size = 20,
  className,
}: {
  name: IconName
  size?: number
  className?: string
}) {
  const Comp: LucideIcon = iconMap[name]
  return <Comp size={size} className={className} strokeWidth={1.75} aria-hidden />
}
